# Generated by Django 3.1 on 2020-09-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_delete_viewborrowlistwithstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewBorrowlistWithStatus',
            fields=[
                ('username', models.CharField(max_length=254, primary_key=True, serialize=False)),
                ('bookname', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('publisher', models.CharField(max_length=30)),
                ('status', models.IntegerField()),
            ],
        ),
    ]
