# Generated by Django 3.1 on 2020-09-14 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_viewborrowlistwithstatus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewBorrowlistWithStatus',
        ),
    ]
